name: Github Package

on:
  workflow_call


env: 
  REGISTRY : ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  bide:
    runs-on: ubuntu-latest
    steps: 

      - name: just for test 1
        run: |
            ls -al
            pwd

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: REgistry Login
        uses: docker/login-action@v3
        with: 
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.BITE_PAT}}
      

      - name: just for test 2
        run: |
          ls -al
          pwd

      - name: Build and push to GH Package
        uses: docker/build-push-action@v4
        with: 
          context: backend
          push: true
          tags: ${{env.REGISTRY}}/jeckops/back-ausecours:latest

      - name: just for test 3
        run: |
            ls -al
            pwd