name: Test

on:
  push:
    branches:
      - main

jobs:
  Backend:
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
        
    steps:
      - name: The First
        run: echo bonjour
        

  test2:
    needs: [test1]
    runs-on: ubuntu-latest
    steps:
      - name: The Second
        run: echo aurevoir


  biterie:
    needs: [test2]
    uses: ./.github/workflows/ghcr.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  CARRATIE:
    needs: [biterie]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit


  CARRATIEV2:
    needs: [CARRATIE]
    uses: ./.github/workflows/canary.yaml
    secrets: inherit
    permissions:
      id-token: write


 
  