name: Test

on:
  push:
    branches:
      - main

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: The First
        run: echo bonjour
        

  test2:
    needs: [test1]
    runs-on: ubuntu-latest
    steps:
      - name: The Second
        run: echo aurevoir